In [1]:
import numpy as np

In [2]:
a = np.arange(5)

In [3]:
a.dtype

dtype('int32')

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
a.shape

(5,)

In [6]:
m = np.array([np.arange(2),np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [7]:
m.shape

(2, 2)

In [8]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
print(a[0,0],a[0,1],a[1,0],a[1,1])

1 2 3 4


In [10]:
np.float64(42)

42.0

In [11]:
np.int8(42.0)

42

In [12]:
np.bool(42)

True

In [13]:
np.bool(0)

False

In [14]:
np.bool(42.0)

True

In [15]:
np.float(True)

1.0

In [16]:
np.float(False)

0.0

In [17]:
np.arange(7, dtype=np.uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [18]:
a = np.array([[1,2],[3,4]])
a.dtype.itemsize

4

In [19]:
np.arange(7, dtype='b') # dtype = i,f,d,b,D

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [20]:
print(np.dtype(np.float),np.dtype('f'),np.dtype('d'),np.dtype('f8'))

float64 float32 float64 float64


In [21]:
np.sctypeDict.keys() #others data types

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 'uintp', 'P', 'long', 'l', 7, 'L', 8, 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int32', 'Int32', 'i4', 'uint32', 'Uint32', 'u4', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'UInt32', 'int64', 'Int64', 'i8', 'uint64', 'UInt64', 'u8', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [22]:
t=np.dtype('Float64')
print(t.char)
print(t.str)
t.type

d
<f8


<ipython-input-22-5d83e13dd0cf>:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  t=np.dtype('Float64')


numpy.float64

In [23]:
t = np.dtype([('name',np.str_,40),('numitems',np.int32), ('price',np.float32)])
print(t)
print(t['name'])

[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')]
<U40


In [24]:
#1d array slicing and indexing
a = np.arange(9)
print(a)
print(a[3:7])
print(a[0:7:2])
print(a[::-1])

[0 1 2 3 4 5 6 7 8]
[3 4 5 6]
[0 2 4 6]
[8 7 6 5 4 3 2 1 0]


In [25]:
#multi dim array slicing and indexing
b = np.arange(24)
print("\n")
print(b)
print("\n")
c = b.reshape(2,3,4)
print(c.ndim) # 3d array
print("\n")
print(c)
print("\n")
print(c[:,0,0])# firsts of the column and row
print("\n")
print(c[0])
print("\n")
print(c[0]) #or c[0,:,:] or c[0, ...]
print("\n")
print(c[0,1])
print("\n")
print(c[0,1,::2])
print("\n")
print(c[0,:,-1])
print("\n")
print(c[0,::-1, -1])
print("\n")
print(c[0,::2,-1])



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


3


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[ 0 12]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[4 5 6 7]


[4 6]


[ 3  7 11]


[11  7  3]


[ 3 11]


In [34]:
# Manipulate array shapes
b = np.arange(24).reshape(2,3,4)
print(b)
print(b.ravel())
print("\n")
print(b.flatten()) # safe but utilizes more memory

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [27]:
b.shape = (6,4)
print(b)
print("\n")
print(b.transpose())
print("\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]




In [28]:
#Stacking : vstack(), dstack(), hstack(), column_stack(), row_stack(),and concatenate()
a = np.arange(9).reshape(3,3)
print(a)
print("\n")
b = 2 * a
print(b)
print("\n")
print(np.hstack((a,b)))
print("\n")
print(np.concatenate((a, b), axis=1)) # same as hstack
print("\n")
print(np.vstack((a,b)))
print("\n")
print(np.concatenate((a, b), axis=0)) # same as vstack
print("\n")
print(np.dstack((a,b)))
print("\n")

oned = np.arange(2)
print(oned)
print("\n")
twice_oned = 2 * oned
print(twice_oned)
print("\n")
print(np.column_stack((oned, twice_oned)))
print("\n")
print(np.column_stack((a, b)) == np.hstack((a, b)))
print("\n")
print(np.row_stack((oned, twice_oned)))
print("\n")
print(np.row_stack((a, b)) == np.vstack((a, b)))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]


[0 1]


[0 2]


[[0 0]
 [1 2]]


[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


[[0 1]
 [0 2]]


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [29]:
# Splitting : hsplit(), vsplit(), dsplit(), and split().
a = np.arange(9).reshape(3,3)
print(a)
print("\n")
print(np.hsplit(a,3))
print("\n")
print(np.split(a, 3, axis=1))
print("\n")
print(np.vsplit(a,3))
print("\n")

c = np.arange(27).reshape(3, 3, 3)
print(c)
print("\n")
print(np.dsplit(c,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]


In [30]:
# array attributes
print(b.ndim)
print(b.size)
print(b.itemsize)
print(b.nbytes) # b.size * b.itemsize
print(b.resize(3,3))
print(b.T)

2
9
4
36
None
[[ 0  6 12]
 [ 2  8 14]
 [ 4 10 16]]


In [31]:
#Complex numbers
b = np.array([1.j + 1, 2.j + 3])
print(b)
print(b.real)
print(b.imag)
print(b.dtype)
print(b.dtype.str)

[1.+1.j 3.+2.j]
[1. 3.]
[1. 2.]
complex128
<c16


In [32]:
#flatiter
b = np.arange(4).reshape(2,2)
print(b)
f = b.flat
print(f)
for item in f:print(item)
print("\n")
print(b.flat[2])
print("\n")
print(b.flat[[1,3]])
print("\n")
b.flat = 7
print(b)

[[0 1]
 [2 3]]
0
1
2
3


2


[1 3]


[[7 7]
 [7 7]]


In [33]:
#converting arrays and complex numbers
print(b.tolist())
b = np.array([(1.+1.j), (3.+2.j)]).astype('complex')
print(b)

[[7, 7], [7, 7]]
[1.+1.j 3.+2.j]
